import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowDownUp, Music2, ReceiptText, Search } from "lucide-react";
import { LifeTraceShell, PageIntro } from "@/components/lifetrace-shell";
import { TraceDialog } from "@/components/trace-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { lifeMoments, type LifeMoment, type MomentCategory } from "@/lib/lifetrace-data";

export const Route = createFileRoute("/moments")({ head: () => ({ meta: [{ title: "Moments — LIFE//TRACE" }, { name: "description", content: "Search the individual music and transaction artifacts inside LIFE//TRACE." }, { property: "og:title", content: "Moments — LIFE//TRACE" }, { property: "og:description", content: "Find a receipt, open its details, and follow nearby traces through time." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: MomentsPage });

const filters: (MomentCategory | "All" | "Transactions")[] = ["All", "Music", "Transactions", "Food", "Transportation", "Subscriptions", "Other"];
function MomentsPage() {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<(typeof filters)[number]>("All"); const [ascending, setAscending] = useState(false); const [selected, setSelected] = useState<LifeMoment | null>(null);
  const results = useMemo(() => lifeMoments.filter((moment) => { const matchesFilter = filter === "All" || (filter === "Transactions" ? moment.kind === "transaction" : moment.category === filter); const haystack = `${moment.title} ${moment.subtitle} ${moment.detail} ${moment.category}`.toLowerCase(); return matchesFilter && haystack.includes(query.toLowerCase()); }).sort((a, b) => (new Date(a.occurredAt).getTime() - new Date(b.occurredAt).getTime()) * (ascending ? 1 : -1)), [query, filter, ascending]);
  return <LifeTraceShell><PageIntro index="04" eyebrow="Moments" title="Find one fragment. Follow where it leads.">The raw artifacts sit beneath every chapter and pattern. Search them without losing the thread.</PageIntro><section className="mx-auto max-w-[1440px] px-5 pb-28 md:px-10">
    <div className="grid gap-4 border-y border-border py-5 md:grid-cols-[1fr_auto]"><label className="relative"><Search className="absolute left-0 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><span className="sr-only">Search moments</span><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search artist, track, merchant, category…" className="h-11 rounded-none border-0 border-b border-border bg-transparent pl-7 shadow-none"/></label><Button variant="ghost" onClick={() => setAscending((value) => !value)}><ArrowDownUp/> {ascending ? "Oldest first" : "Newest first"}</Button></div>
    <div className="flex gap-5 overflow-x-auto border-b border-border py-4" aria-label="Filter moments">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`shrink-0 border-b pb-1 text-xs focus-visible:outline-2 focus-visible:outline-ring ${filter === item ? "border-foreground text-foreground" : "border-transparent text-muted-foreground"}`}>{item}</button>)}</div>
    {results.length ? <div className="mt-10 columns-1 gap-5 sm:columns-2 lg:columns-3 xl:columns-4">{results.slice(0, 40).map((moment, index) => <button key={moment.id} onClick={() => setSelected(moment)} className={`mb-5 inline-block w-full break-inside-avoid border border-border bg-card p-5 text-left shadow-paper transition-transform hover:-translate-y-1 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring ${index % 3 === 1 ? "rotate-[0.35deg]" : index % 5 === 0 ? "-rotate-[0.3deg]" : ""}`}><div className="flex justify-between">{moment.kind === "music" ? <Music2 className="size-4 text-dusty-blue"/> : <ReceiptText className="size-4 text-ochre"/>}<span className="font-mono text-[9px] uppercase text-muted-foreground">{new Date(moment.occurredAt).toLocaleDateString()}</span></div><h2 className="mt-12 font-display text-3xl leading-tight">{moment.title}</h2><p className="mt-2 text-xs text-muted-foreground">{moment.subtitle}</p><div className="mt-8 border-t border-dashed border-border pt-3 text-[11px] text-muted-foreground">{moment.detail}{moment.value ? ` · $${moment.value.toFixed(2)}` : ""}</div></button>)}</div> : <div className="py-28 text-center"><h2 className="font-display text-4xl">No matching traces.</h2><p className="mt-3 text-sm text-muted-foreground">Try a broader word or choose All.</p><Button className="mt-6" onClick={() => { setQuery(""); setFilter("All"); }}>Clear search</Button></div>}
  </section><TraceDialog moment={selected} moments={lifeMoments} open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)} onMomentChange={setSelected}/></LifeTraceShell>;
}